/** @ops-pi/core —— 运维原子能力（L1）：不依赖 omp / Yuyi / 任何宿主（方案 §7.1） */
export { OpsError } from "./errors.ts";
export type { OpsErrorCode } from "./errors.ts";
export { ShellExec } from "./exec.ts";
export type { ExecResult, ExecOptions } from "./exec.ts";
export { FileOps } from "./files.ts";
export type { FileReadOptions } from "./files.ts";
export { ProcessManager, parsePsOutput } from "./process.ts";
export type { ProcessInfo, ProcessListOptions } from "./process.ts";
export { criticalReason } from "./content-guard.ts";
export { LogCollector } from "./log.ts";
export type { TailResult, JournalctlResult, GrepResult } from "./log.ts";
export { loadTargetPolicy, DefaultDenyPolicy, ReloadableTargetPolicy, LOCAL_HOST, statMtimeMs, ruleActive, traceRule, traceRules } from "./policy.ts";
export type { TargetPolicy, TargetRule, PolicyFile, PolicyRequest, RuleTrace } from "./policy.ts";
export { loadTokenStore, StaticTokenStore, ReloadableTokenStore, tokenActive, tokenCovers, traceTokens } from "./tokens.ts";
export type { ApprovalToken, TokenFile, TokenStore, TokenTrace } from "./tokens.ts";
export { lintPolicySource, lintPolicyRules, lintTokenSource, summarizeLint } from "./policy-lint.ts";
export type { LintFinding, LintLevel, LintOptions, ActionVocabulary } from "./policy-lint.ts";
export { READ, WRITE, EXEC, byAction, tierOf, needsOwnerAuth, createAuthorizedExec, evaluateAuthorization } from "./approvals.ts";
export type { Tier, ApprovalDecision, AuthzSource, AuthorizationVerdict } from "./approvals.ts";
export { SshPool, normalizeTargetHost, type SshConfig } from "./ssh.ts";
export { parseGitVersion, versionAtLeast, capsFor, detectGitCaps, GitCompat } from "./git-compat.ts";
export type { GitCaps, GitStep } from "./git-compat.ts";
export type { Runner } from "./runner.ts";
export { CredentialVault } from "./vault.ts";
export { AuditLog, AUDIT_GENESIS, hashRecord } from "./audit.ts";
export type { AuditData, AuditRecord, AuditVerifyResult } from "./audit.ts";
export { PathGuard, realize } from "./path-guard.ts";
export type { PathGuardRoots } from "./path-guard.ts";
